-- Migration: Add SELECT RLS policies for user-owned tables
-- Generated by AI assistant on 2025-07-02

-- Enable RLS for all relevant tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE studentvue_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE canvas_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE music_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE kid_mode_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE feelings ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- SELECT policies for user-owned tables
CREATE POLICY "Users can view their own profile"
  ON profiles
  FOR SELECT
  USING (id = auth.uid());

CREATE POLICY "Users can view their own studentvue credentials"
  ON studentvue_credentials
  FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "Users can view their own canvas credentials"
  ON canvas_credentials
  FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "Users can view their own music connections"
  ON music_connections
  FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "Users can view their own kid mode settings"
  ON kid_mode_settings
  FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "Users can view their own feelings"
  ON feelings
  FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "Users can view their own journal entries"
  ON journal_entries
  FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "Users can view their own tasks"
  ON tasks
  FOR SELECT
  USING (user_id = auth.uid()); 